/*
*
*
*
*
*
*
*
*
*
*
*
*       DO NOT EDIT THIS FILE
*       For FCC testing purposes!
*
*
*
*
*
*
*
*
*/

'use strict';

module.exports = function (app) {
  app.route('/_api/server.js')
    .get(function(req, res, next) {
      console.log('requested');
      res.sendFile(process.cwd() + '/server.js');
    });
  app.route('/_api/routes/api.js')
    .get(function(req, res, next) {
      console.log('requested');
      res.sendFile(process.cwd() + '/routes/api.js');
    });
};
